# --- API Connection
api.base_url=http://localhost:8000/api
api.token=1|fnccfhDzYt3ivRavfkGj7W2RVjCsfnN8JcN56MaX39756c7a
api.device_id=1

# --- Performance
# Check for commands every 1 seconds per 1000
agent.poll_interval=1000
# Connection timeout
agent.timeout=10000

