# --- API Connection
api.base_url=http://localhost:8000/api
api.token=1|fnccfhDzYt3ivRavfkGj7W2RVjCsfnN8JcN56MaX39756c7a
api.device_id=019e4eb1-becc-722e-8db0-693386630d8d

# --- Polling
# Check for commands every 1 seconds per 1000
poll.max_interval_sec=1
# Connection timeout
poll.timeout_sec=60

# --- Logs
log.max_lines=30

